name = "ModelExploration"
uuid = "ee4b7b2d-0795-4448-a530-9f52182b79fb"
authors = ["Kris <ksb@stanford.edu>", "Tyler <t.hanks@ufl.edu>"]
version = "0.1.0"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
